### ISSUE TITLE
crawler - tests failing - see output

### ISSUE THREAD

**Issue by drumm91UWO** [aosabook/500lines#254]
The crawler project's test.py is failing during the setup of every test but I am not familiar enough with asyncio to understand why. System information:
Windows 10
Python 3.5

Here is the output:

C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py:54: ResourceWarning: loop argument is deprecated
  warnings.warn("loop argument is deprecated", ResourceWarning)
EEEEEEEEEEEEEEEEE
======================================================================
ERROR: test_content_type (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_deep_root (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_encoding (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_exclude (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_lenient_host_checking (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_link (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_link_cycle (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_max_tasks (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_max_tries (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_non_html (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_non_http (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_prohibited_host (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_redirect (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_redirect_cycle (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_redirect_join (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_roots (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

======================================================================
ERROR: test_strict_host_checking (__main__.TestCrawler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 51, in setUp
    self.app = self.loop.run_until_complete(self._create_server())
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "test.py", line 64, in _create_server
    handler_factory = app.make_handler(debug=True)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 224, in make_handler
    self._set_loop(loop)
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\web.py", line 110, in _set_loop
    loop = asyncio.get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 589, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Users\Primary User\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 535, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'MainThread'.

----------------------------------------------------------------------
Ran 17 tests in 0.031s

FAILED (errors=17)

**Comment by drumm91UWO** [comment]
I found the solution. The aiohttp 2.0.4 package that I was using depreciated some parts of aiohttp 0.21.x. Using aiohttp 0.21.x fixed the problem.

**Comment by lesssn** [comment]
Can you tell me what's changed?
